feat: support Casbin FilteredAdapter interface
php-casbin/laravel-authz pull request #13
Opened 2021-03-24 14:53 UTC by basakest

2021-03-24 16:15 UTC, hsluoyz commented
@techoner please review.

2021-03-26 04:00 UTC, techoner requested changes

2021-03-26 04:00 UTC, techoner commented on src/Adapters/DatabaseAdapter.php
> +            $instance = $instance->where($filter[0], $filter[1]);
Use `whereRaw()` directly :
```
$instance->whereRaw($filter);
```

2021-04-01 05:39 UTC, closed without merging

2021-04-01 10:20 UTC, hsluoyz commented
Replaced by: https://github.com/php-casbin/laravel-authz/pull/17