feat: Add type parameter to artisan commands
php-casbin/laravel-authz pull request #68
Opened 2024-05-23 12:02 UTC by Dobmod

2024-05-23 13:26 UTC, hsluoyz commented
@leeqvip plz review

2024-05-23 15:28 UTC, leeqvip requested changes

2024-05-23 15:28 UTC, leeqvip commented on README.md
> +php artisan role:assign eve writer --type=g2
Please use `ptype` instead of `type` to ensure consistency with the code.
`--ptype` is not required, so two usages should be retained.

2024-05-23 15:28 UTC, leeqvip commented on tests/Commands/RoleAssignTest.php
> +        $this->assertTrue(Enforcer::hasNamedGroupingPolicy('g', 'eve', 'writer'));
Please keep the default test cases and add new test cases specifying `ptype`

2024-05-24 01:05 UTC, leeqvip requested changes
Please fix ci errors.

2024-05-24 04:49 UTC, Dobmod commented
@leeqvip Sorry, due to my lack of proficiency, I caused a lot of trouble. I have corrected it this time.

2024-05-24 04:50 UTC, Dobmod commented
@leeqvip Sorry, due to my lack of proficiency, I caused a lot of trouble. I have corrected it this time.plz review

2024-05-24 04:56 UTC, hsluoyz commented
@leeqvip

2024-05-24 05:39 UTC, leeqvip approved these changes

2024-05-24 05:39 UTC, merged

2024-05-24 05:42 UTC, leeqvip commented
:tada: This PR is included in version 3.2.0 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/laravel-authz/releases/tag/v3.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: