feat: loading model from remote url
php-casbin/laravel-authz pull request #69
Opened 2024-06-11 14:52 UTC by rev3z

## Description
This PR introduces a feature enabling the Enforcer to initialize by fetching its model configuration from a remote URL. 

Upon initialization, the EnforcerManager will send an HTTP request to the specified URL to retrieve the model strings, thereby loading model from remote machines.

## Related Issues
[Question] Loading model from a remote URL #15

## Details
- Only support plain text response from remote url:  Users who require advanced handling of JSON or other content types are encouraged to process the data fetching in their application logic, ensuring they have full control over deserialization and any subsequent manipulations.
- Remote model load upon initialization: The remote model is fetched only once during setup, implying no cache refreshing mechanism for the model [[See ref]](https://casbin.org/docs/model-storage).
- Ultilizing Laravel's HTTP client for simplicity.

2024-06-11 15:11 UTC, hsluoyz commented
@leeqvip plz review

2024-06-11 15:57 UTC, leeqvip requested changes
And please add `unit tests`

2024-06-11 15:57 UTC, leeqvip commented on src/EnforcerManager.php
> +            $resp = Http::accept('text/html')
plz use `text/plain`

2024-06-12 15:27 UTC, leeqvip commented
@rev3z Please fix the ci check error.

2024-06-12 15:40 UTC, rev3z commented
I'll fix it！

2024-06-14 16:15 UTC, rev3z commented
CI error fixed, PR contents updated.

2024-06-15 00:24 UTC, hsluoyz commented
@leeqvip plz review

2024-06-15 17:00 UTC, leeqvip approved these changes

2024-06-15 17:18 UTC, merged

2024-06-15 17:21 UTC, leeqvip commented
:tada: This PR is included in version 3.3.0 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/laravel-authz/releases/tag/v3.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: